services:
    kernel.listener.exception_listener:
        class: Intellias\TestBundle\Listener\ExceptionListener
        arguments: [@templating, @kernel]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
